# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Greenhouse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Greenhouse
  pod 'Onboard'
  pod "RMPZoomTransitionAnimator"
  pod 'LGPlusButtonsView', '~> 1.1.0'
  pod 'SCLAlertView-Objective-C'
end
