//
//  GoogleIdentityProfile.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
//

#import <Foundation/Foundation.h>
#import <AWSMobileHubHelper/AWSIdentityProfile.h>

@interface GoogleIdentityProfile : NSObject<AWSIdentityProfile>

/**
 Fetches the shared instance for GoogleIdentityProfile.
 
 @return the single instance of GoogleIdentityProfile
 */
+ (instancetype)sharedInstance;

@end
