//
//  SignInViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
//
#import <UIKit/UIKit.h>

@interface SignInViewController : UIViewController

@property (atomic) BOOL canCancel;

//@property (weak, nonatomic) IBOutlet UIButton *twitterButton;
@property (weak, nonatomic) IBOutlet UIButton *googleButton;
// Support code for Amazon provider UI.
//@property (weak, nonatomic) IBOutlet UIButton *amazonButton;

@property (nonatomic, copy) void (^didCompleteSignIn)(BOOL success);

@end
