//
//  AppDelegate.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
#import "AppDelegate.h"
#import "AWSMobileClient.h"
#import "SignInViewController.h"
#import <Onboard/OnboardingViewController.h>
#import <Onboard/OnboardingContentViewController.h>

@interface AppDelegate ()

@end

static NSString * const kUserHasOnboardedKey = @"user_has_onboarded";

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    NSLog(@"application didFinishLaunchingWithOptions");
    // determine if the user has onboarded yet or not
    BOOL userHasOnboarded = [[NSUserDefaults standardUserDefaults] boolForKey:kUserHasOnboardedKey];
    
    if (userHasOnboarded) {
//        [self setupNormalRootViewController];
        self.window.rootViewController = [self generateStandardOnboardingVC];
    }
    else {
        self.window.rootViewController = [self generateStandardOnboardingVC];
    }
    
//    application.statusBarStyle = UIStatusBarStyleLightContent;
    
    [self.window makeKeyAndVisible];
    
    // Override point for customization after application launch.
    return [[AWSMobileClient sharedInstance] didFinishLaunching:application
                                             withOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    NSLog(@"application application: %@, openURL: %@, sourceApplication: %@", application.description, url.absoluteURL,
          sourceApplication);

    return [[AWSMobileClient sharedInstance] withApplication:application
                                                     withURL:url
                                       withSourceApplication:sourceApplication
                                              withAnnotation:annotation];
}

- (void)setupNormalRootViewController {
    UIStoryboard *loginStoryboard = [UIStoryboard storyboardWithName:@"SignIn"
                                                              bundle:nil];
    SignInViewController *loginController = (SignInViewController *)[loginStoryboard instantiateViewControllerWithIdentifier:@"NavController"];
    
    CATransition * animation = [CATransition animation];
    animation.duration = 0.6;
    animation.type = kCATransitionFade;
    [self.window.rootViewController.view.window.layer addAnimation:animation forKey:nil];
    [self.window.rootViewController presentViewController:loginController
                                                 animated:NO completion:nil];
}

- (void)handleOnboardingCompletion {

    [[NSUserDefaults standardUserDefaults] setBool:YES forKey:kUserHasOnboardedKey];
    
    [self setupNormalRootViewController];
}

- (OnboardingViewController *)generateStandardOnboardingVC {
    CGRect screenRect = [[UIScreen mainScreen] bounds];
    CGFloat screenWidth = screenRect.size.width;
    
    OnboardingContentViewController *firstPage = [OnboardingContentViewController contentWithTitle:@"Sensor" body:@"透過 IoT Sensor\n監測溫度、濕度、光度" image:[UIImage imageNamed:@"feature1"] buttonText:nil action:nil];
    firstPage.iconHeight = screenWidth*3/5;
    firstPage.iconWidth = screenWidth*3/5;
    firstPage.topPadding = 100;
    firstPage.titleLabel.font = [UIFont fontWithName:@"Chalkboard SE" size:38];
    firstPage.bodyLabel.font = [UIFont fontWithName:@"Calibri" size:24];
    
    OnboardingContentViewController *secondPage = [OnboardingContentViewController contentWithTitle:@"Webpage" body:@"透過網頁\n掌握第一手即時資訊" image:[UIImage imageNamed:@"feature2"] buttonText:nil action:nil];
    secondPage.iconHeight = screenWidth*3/5;
    secondPage.iconWidth = screenWidth*3/5;
    secondPage.topPadding = 100;
    secondPage.titleLabel.font = [UIFont fontWithName:@"Chalkboard SE" size:38];
    secondPage.bodyLabel.font = [UIFont fontWithName:@"Calibri" size:24];
    
    OnboardingContentViewController *thirdPage = [OnboardingContentViewController contentWithTitle:@"Customized" body:@"客製化調整\n溫度、濕度、光度控管" image:[UIImage imageNamed:@"feature3"] buttonText:@"Get Started" action:^{
        [self handleOnboardingCompletion];
    }];
    thirdPage.iconHeight = screenWidth*3/5;
    thirdPage.iconWidth = screenWidth*3/5;
    thirdPage.topPadding = 100;
    thirdPage.titleLabel.font = [UIFont fontWithName:@"Chalkboard SE" size:38];
    thirdPage.bodyLabel.font = [UIFont fontWithName:@"Calibri" size:24];
    
    OnboardingViewController *onboardingVC = [OnboardingViewController onboardWithBackgroundImage:[UIImage imageNamed:@"banner1"] contents:@[firstPage, secondPage, thirdPage]];
    onboardingVC.shouldFadeTransitions = YES;
    onboardingVC.fadePageControlOnLastPage = YES;
    onboardingVC.fadeSkipButtonOnLastPage = YES;
    onboardingVC.shouldBlurBackground = YES;
    
    // If you want to allow skipping the onboarding process, enable skipping and set a block to be executed
    // when the user hits the skip button.
    onboardingVC.allowSkipping = YES;
    onboardingVC.skipHandler = ^{
        [self handleOnboardingCompletion];
    };
    
    return onboardingVC;
}

- (void)applicationWillResignActive:(UIApplication *)application {
    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
}

- (void)applicationWillTerminate:(UIApplication *)application {
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
}
- (BOOL)prefersStatusBarHidden {
    return NO;
}

@end
